Create contact
Paul-Wallstone/diary pull request #5
Opened 2022-05-30 18:53 UTC by commandoby

2022-05-30 20:07 UTC, Paul-Wallstone requested changes
Оставил комменты

2022-05-30 20:07 UTC, Paul-Wallstone commented on src/main/java/by/school/diary/service/ContactService.java
> +    void delete(ContactEntity contactEntity);
старайся форматировать код.. отступы и тд.

2022-05-30 20:07 UTC, Paul-Wallstone commented on src/main/java/by/school/diary/service/impl/ContactServiceImpl.java
> +	public ContactEntity getById(Long id) {
нужно создать Dto например ContactRequestDto и конвертить в него прямо в сервисе

2022-05-30 20:07 UTC, Paul-Wallstone commented on src/main/java/by/school/diary/service/impl/ContactServiceImpl.java
> +	public ContactEntity getById(Long id) {
public ContactRequestDto getById(Long id) {
ContactEntity  contactEntity  =contactRepository.findById(id).orElseThrow(() -> new ContactNotFoundException(id));
return modelMapper.toDto(contactEntity);

в CustomModelMapper добавить переопределение toDto и toEntity

2022-05-30 20:07 UTC, Paul-Wallstone commented on src/main/java/by/school/diary/exception/ContactNotFoundException.java
> +public class ContactNotFoundException extends RuntimeException {
Для  ошибки нужно добавить обработчик в ControllerAdvisor, который отправляет response  по типовой форме

2022-05-30 20:07 UTC, Paul-Wallstone commented on src/main/java/by/school/diary/service/impl/ContactServiceImpl.java
> +		}
ContactRepository:
Optional<ContactEntity> findByContactEntity(ContactEntity contactEntity);
затем:
if(contactRepository.findByContactEntity(contactEntity).isPresent()){

2022-05-30 20:36 UTC, commandoby commented on src/main/java/by/school/diary/service/ContactService.java
> +    void delete(ContactEntity contactEntity);
Забыл прожать форматирование в конце.

2022-05-30 20:38 UTC, commandoby commented on src/main/java/by/school/diary/service/impl/ContactServiceImpl.java
> +	public ContactEntity getById(Long id) {
Я пока не до конца понимаю смысл этих Dto. Погуглю в следующий раз.

2022-05-30 20:38 UTC, commandoby commented on src/main/java/by/school/diary/exception/ContactNotFoundException.java
> +public class ContactNotFoundException extends RuntimeException {
Ок. Добавлю.

2022-05-30 20:39 UTC, commandoby commented on src/main/java/by/school/diary/service/impl/ContactServiceImpl.java
> +		}
Да, так будет лучше.

2022-05-31 22:01 UTC, Paul-Wallstone approved these changes

2022-06-01 18:15 UTC, merged